version: '3.7'
services:
  traefik:
    image: traefik:v2.1.3
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - "TZ=Asia/Seoul"
    command:
      # default
      - "--log.level=info"
      #- "--log.format=json"
      #- "--global.checkNewVersion=true"
      #- "--global.sendAnonymousUsage=false"
      #- "--api=true"
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--ping=true"

      # cert
      - "--certificatesresolvers.swarm-proxy.acme.httpchallenge=true"
      - "--certificatesresolvers.swarm-proxy.acme.httpchallenge.entrypoint=entrypoint-http"
      - "--certificatesresolvers.swarm-proxy.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.swarm-proxy.acme.email=${EMAIL}"
      - "--certificatesresolvers.swarm-proxy.acme.storage=/certs/acme.json"

      # entrypoints
      - "--entrypoints.entrypoint-http.address=:80"
      - "--entrypoints.entrypoint-https.address=:443"

      # providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmmode=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs:/certs
    configs:
      - source: traefik_htpasswd
        target: /etc/htpasswd
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=public"
        - "traefik.http.services.frontend-traefik.loadbalancer.server.port=8080"

        - "traefik.http.routers.unsecured-traefik.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.unsecured-traefik.entrypoints=entrypoint-http"
        - "traefik.http.routers.unsecured-traefik.middlewares=secured-redirectscheme@docker"
        - "traefik.http.middlewares.secured-redirectscheme.redirectscheme.scheme=https"

        - "traefik.http.routers.secured-traefik.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.secured-traefik.entrypoints=entrypoint-https"
        - "traefik.http.routers.secured-traefik.service=api@internal"
        - "traefik.http.routers.secured-traefik.tls=true"
        - "traefik.http.routers.secured-traefik.tls.certresolver=swarm-proxy"
        - "traefik.http.routers.secured-traefik.middlewares=basicauth-traefik@docker"
        - "traefik.http.middlewares.basicauth-traefik.basicauth.usersfile=/etc/htpasswd"


configs:
  traefik_htpasswd:
    file: ./htpasswd

networks:
  public:
    driver: overlay
    name: public

volumes:
  traefik_certs: {}
